web:
  restart: always
  build: .
  volumes:
    - fonts:/app/static/fonts
  ports:
    - "80:80"
  links:
    - db
  environment:
    - RDB_HOST=db

db:
  image: rethinkdb
  command: rethinkdb --bind all -d /data
  volumes:
    - /data:/data