web:
  restart: always
  build: .
  volumes:
    - fonts:/app/static/fonts
    - media:/app/static/media
  ports:
    - "80:80"
  links:
    - db
  environment:
    - RDB_HOST=db
    - GFR_DO_NOT_DIFF_FAMILIES=True
    - GFR_PRODUCTION_MODE=True

db:
  image: rethinkdb
  command: rethinkdb --bind all -d /data
  volumes:
    - /data:/data
